main-class: decadence.tests.decadence.tests.Main

# [a-z0-9_-]
plugin-id: "test_plugin"
# [a-zA-Z0-9_-]
plugin-name: "Test Plugin"

# /neco-test:some-command
# If it`s null - Module use module_id for command prefix
command-prefix: "topaz-test"

# true - Enable message list file (messages.yml)
# false - Disable it
message-list: true

# If u need share plugin api
contains-api: true
